name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: ssh key generate
        run: echo "$SAKURA_SSH_KEY" > key && chmod 600 key
        env:
          SAKURA_SSH_KEY: ${{ secrets.SAKURA_SSH_KEY }}

      - name: rsync deploy
        run: rsync -rptgDvz --delete -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./home/ubuntu/degime-backend* ubuntu@133.242.184.231:/home/ubuntu


      - name: ssh key generate again
        run: echo "$SAKURA_SSH_KEY" > key && chmod 600 key
        env:
          SAKURA_SSH_KEY: ${{ secrets.SAKURA_SSH_KEY }}

      - name: rsync deploy again
        run: rsync -rptgDvz --delete -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./etc/nginx/conf.d* ubuntu@133.242.184.231:/etc/nginx/conf.d


      - name: pip update
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r ./home/ubuntu/degime-backend/requirements.txt
      
      - name: Run makemigrations
        run: python ./home/ubuntu/degime-backend/manage.py makemigrations

      - name: Run migrations
        run: python ./home/ubuntu/degime-backend/manage.py migrate

      - name: Run migrations
        run: python ./home/ubuntu/degime-backend/manage.py test
