name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Specify your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: ssh key generate
        run: echo "$SAKURA_SSH_KEY" > key && chmod 600 key
        env:
          SAKURA_SSH_KEY: ${{ secrets.SAKURA_SSH_KEY }}
      - name: rsync deploy
        run: rsync -rptgDvz --delete -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./home/ubuntu/degime-backend/* ubuntu@133.242.184.231:/home/ubuntu/degime-backend

      - name: Collect static files
        run: python manage.py collectstatic

      - name: Run migrations
        run: python manage.py migrate

      - name: Start ASGI server (example with Uvicorn)
        run: uvicorn --host 0.0.0.0 --port 8000 asgi:application  # Adjust host and port as needed